### ISSUE TITLE
Please Change Color Choices

### ISSUE THREAD

**Issue by DixonAgee** [Zivi/FlattestRoute#11]
I love flattestroute and find that it is also useful for modes of transportation other than bikes, e.g. cars pulling trailers.  However your color choices for slope are counter-intuitive.  Normally folks would look at the progression of slopes go from cool (green or blue) to hot (red).  Rather than give you my personal preferences, I'd like to give you a single suggestion.  

Please change the Difficult Range (10% to 15% slope)  from its current Blue to Orange, which flows logically between the yellow and red ranges.  Thanks for your consideration.

Bruce Agee

**Comment by Zivi** [comment]
Thanks for the suggestion. I've updated the colour.
Zivi

**Comment by DixonAgee** [comment]
Hi Zivi -

Excellent!  It it much easier to interpret, now.  And as a reward, here's a view of Sonora Pass with Flattest Route.  The pass claims a max 26% slope.  This is not quite seen by your program, but I figure it is a function of the topo info and trip length chosen.  Regardless, the route still looks mighty steep.  Sonora Pass  Zoom in for the detail.

I also want to point out an oddity - several green roads not connected to the highway show up in the map..  My guess it's a side-product of the Google API.  I wonder if they are aware of this behavior.  (It doesn't bother me).

Thanks again for your rapid response and for a useful program!

- Bruce Agee



 

 

 

-----Original Message-----
