### ISSUE TITLE
distance unit selection not working

### ISSUE THREAD

**Issue by michaelwemoto** [Zivi/FlattestRoute#18]
Selecting Miles or Kilometers outputs kilometers.

**Comment by Zivi** [comment]
@michaelwemoto I tried to reproduce the issue and am able to toggle between miles and kilometres. Please provide the steps you made to trigger this issue.

**Comment by michaelwemoto** [comment]
simply loaded the page, I'm running Fedora, using Google Chrome Version 49.0.2623.108 (64-bit).

That was the fastest response I have seen on github! Especially on a project you published two years ago, well done! I've clone and modified the bootstrap layout a little too, increasing the elevation / slope graphs to full width, could you point me to where I can increase the detail of the elevation / slope charts? Currently planning a 500Km trip from Brighton (UK) to Arlon, Belgium... amazing tool! would be handy to have a function to say 'split this route into 4 even days taking into consideration elevation / climbs etc'...

**Comment by michaelwemoto** [comment]
switching to Kilometers gives me a float to three decimal places, Miles there are no decimals, same number though...

**Comment by Zivi** [comment]
OK, I see the issue now. In regions where the unit of distance measurement is metric, the search defaults to km, but for regions with imperial measurement, it defaults to miles. I deployed a fix for that. Now the distance measurement is based on what is selected on the page.

The elevation chart code is in main.js lines 191-233. Slope chart code is lines 234-272.

Feel free to make any additional changes and send me a pull request if you would like it integrated into the page.
