### ISSUE TITLE
Google Maps don't load in single instance mode

### ISSUE THREAD

**Issue by StratSwede** [Zivi/FlattestRoute#21]
I downloaded the zip file, unzipped and tried to run the file.  I get numerous errors that this page can't load google maps correctly.  Any thoughts?

Here are the errors listed in firefox web console:

Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# insteadjquery-1.9.1.min.js:1
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.jquery-1.9.1.min.js:3:31293
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.index.html
"You have exceeded your request quota for this API. See https://developers.google.com/maps/documentation/javascript/error-messages?utm_source=maps_js&utm_medium=degraded&utm_campaign=billing#api-key-and-billing-errors"js:58:110

"You have exceeded your request quota for this API. See https://developers.google.com/maps/documentation/javascript/error-messages?utm_source=maps_js&utm_medium=degraded&utm_campaign=billing#api-key-and-billing-errors"js:58:110

"Google Maps JavaScript API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys"util.js:219:12
"Google Maps JavaScript API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required"util.js:219:12

**Comment by Zivi** [comment]
The errors you are seeing the console is expected. I am no longer maintaining this site because of the new pricing for Google Maps. To remove the error messages you need to set up an API key with Google Maps.  Google Maps' API documentation will give you instructions for how to do that.
